"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..");
const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(match => match[1]);
assert.equal(new Set(ids).size, ids.length, "HTML IDs must be unique");
assert.ok(!html.includes("user-scalable=no"), "Browser zoom must remain available");
assert.ok(!html.includes("gesturestart','gesturechange','gestureend"), "Gesture zoom blocking must remain removed");
assert.ok(html.includes("touch-action:pan-x pan-y pinch-zoom"), "Touch zoom must remain available");
assert.ok(html.includes('<a class="skip-link" href="#main">'), "Skip link is present");
assert.ok(html.includes('<main id="main">'), "Main landmark is present");
assert.ok(html.includes('<link rel="icon" href="/favicon.svg" type="image/svg+xml">'), "Favicon is linked");
assert.ok(html.includes('content="https://freeman-ipumbu.pages.dev/social-preview-v3.jpg"'), "Social preview uses the current versioned production origin");
assert.ok(html.includes('<meta property="og:image:width" content="1200">'));
assert.ok(html.includes('<meta property="og:image:height" content="630">'));
assert.ok(html.includes('<meta name="twitter:image:alt"'));
assert.ok(html.includes('type="application/ld+json"'), "Person structured data is present");
const structuredData = html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
assert.ok(structuredData, "Structured data block can be located");
assert.doesNotThrow(() => JSON.parse(structuredData[1]), "Structured data is valid JSON");
assert.ok(html.includes('"jobTitle":"Technical Director"'), "Structured data leads with the current TPTS role");
assert.ok(html.includes('"name":"TPTS Namibia"'), "TPTS Namibia is represented in structured data");
assert.ok(!/\son(?:click|error|load)=/i.test(html), "No inline event handlers");
assert.ok(html.includes("Technical Director, TPTS Namibia"), "Current TPTS leadership role is visible");
assert.ok(html.includes("Founder and CEO, SolarSpin Technologies"), "SolarSpin founder identity is visible");
assert.ok(html.includes("Founder and CEO, Runnerz Namibia"), "Runnerz founder identity is visible");
assert.ok(html.includes("Co-Founder and CTO, RightMatch Namibia"), "RightMatch technical leadership is visible");
assert.ok(html.includes("20 July 2026 to 15 September 2026"), "The Namibian role has the confirmed closed dates");
assert.ok(html.includes("LIVE // FIELD COMMAND 2"), "Omutambo release signal is current");
assert.ok(html.includes("100 AUTOMATED CHECKS"), "Omutambo verification evidence is visible");
assert.ok(html.includes("cattle, goats, sheep, freely named livestock"), "Omutambo multi-species scope is visible");
assert.ok(html.includes("projects/magic-boys-fa-logo.png"), "Magic Boys uses the approved standalone academy crest");
assert.ok(html.includes("evidence coverage behind poultry measures"), "Omutambo evidence-coverage refresh is visible");
assert.ok(html.includes("UNIFIED 20.0 — Signal Command"), "Current UNIFIED release is visible");
assert.ok(html.includes("projects/unified-20-command-deck.png"), "UNIFIED uses current physical Command Deck proof");
assert.ok(html.includes("version code 22"), "UNIFIED Play version-code evidence is visible");
assert.ok(html.includes('class="build-card flagship" id="unified"'), "UNIFIED has a shareable flagship anchor");
assert.ok(html.includes("five evidence-led Smart Spaces"), "Continuum scope is visible");
assert.ok(html.includes("physical Capsule export/restore"), "UNIFIED device evidence is explicit");
assert.ok(html.includes("aggregate-only completion contract"), "Runnerz privacy boundary is explicit");
assert.ok(html.includes("GOOGLE PLAY REVIEW // RUNNERZ 1.1.0 · CODE 16"), "Runnerz Play review signal is current");
assert.ok(html.includes("projects/runnerz-1.1.0.png"), "Runnerz uses current controlled handset proof");
assert.ok(html.includes('class="build-card flagship runnerz-release" id="runnerz"'), "Runnerz has a shareable flagship anchor");
assert.ok(html.includes("145 TESTS PER VARIANT / 0 FAILURES"), "Runnerz automated-test evidence is visible");
assert.ok(html.includes("exact trails stay local"), "Runnerz trail privacy boundary is visible");
assert.ok(html.includes("12-testers-for-14-days production gate remain tracked work"), "Runnerz production-access boundary is visible");
assert.ok(html.includes("GOOGLE PLAY // LAUNCH LANE"), "Current Google Play launch lane is prominent");
assert.ok(html.includes("UNIFIED 20.0 · CODE 22"), "UNIFIED Alpha build identity is current");
assert.ok(html.includes("https://play.google.com/apps/testing/com.unified.music"), "UNIFIED tester opt-in is linked");
assert.ok(html.includes("12+ OPTED-IN TESTERS FOR 14 CONTINUOUS DAYS"), "Shared Google Play production gate is explicit");
assert.ok(!html.includes('src="projects/runnerz.webp"'), "Legacy Runnerz banner is no longer referenced");
assert.ok(html.includes("EARLY ACCESS EXPANDED // APPROVALS PENDING"), "RightMatch launch gate is current");
assert.ok(html.includes("dedicated renter, owner and small-business paths"), "RightMatch business pathway is current");
assert.ok(html.includes("six-vehicle featured view"), "RightMatch discovery refresh is current");
assert.ok(html.includes("transparent owner-income calculator"), "RightMatch calculator is current");
assert.ok(html.includes("final Namibian legal, insurance, identity and operational approvals"), "RightMatch external approvals remain explicit");
assert.ok(html.includes('class="build-card flagship" id="rightmatch"'), "RightMatch has a shareable flagship anchor");
assert.ok(html.includes("42 valid directional journeys"), "Borizago directional route scope is current");
assert.ok(html.includes("monthly financial/customer reporting"), "Borizago reporting scope is current");
assert.ok(html.includes("borizago-staff-guide.pdf"), "Borizago staff guide is linked");
assert.ok(html.includes("projects/borizago-refined-v2.png"), "Borizago uses the local refined identity asset");
assert.ok(html.includes("ALL RIGHTS RESERVED"), "Portfolio ownership notice is visible");
assert.ok(html.includes("A DIGITAL EXPERIENCE BY") && html.includes(">SOLARSPIN TECHNOLOGIES</a>"), "Linked SolarSpin experience credit is visible");
assert.ok(html.includes('id="fuel-retail-platform"'), "Anonymous fuel-retail case study is featured");
assert.ok(html.includes("It is not a live financial service"), "Fuel-retail public boundary is explicit");
assert.ok(html.includes("fuel-retail-digital-platform-case-study"), "Fuel-retail public repository is linked");
assert.ok(html.includes('href="https://titos-barber.pages.dev/"'), "Tito On Call live experience is linked");
assert.ok(html.includes('href="https://github.com/freeman-ipumbu/tito-on-call-case-study"'), "Tito On Call case study is linked");
assert.ok(html.includes("projects/tito-on-call.svg"), "Tito On Call uses its launch identity artwork");
assert.ok(html.includes('id="monaluxe-circle"'), "Mona Luxe Circle has a shareable flagship anchor");
assert.ok(html.includes('href="https://monaluxe.pages.dev/"'), "Mona Luxe live experience is linked");
assert.ok(html.includes('href="https://github.com/freeman-ipumbu/monaluxe-case-study"'), "Mona Luxe public case study is linked");
assert.ok(html.includes("projects/monaluxe-card.webp"), "Mona Luxe uses its PII-free final brand artwork");
assert.ok(html.includes("Mona Luxe Circle rewards and referrals"), "Mona Luxe client-retention system is represented");
assert.ok(html.includes("private StudioDesk for appointments, payments, client value and retention insight"), "Mona Luxe StudioDesk scope is represented");
assert.ok(html.includes("beginner options with or without a kit, advanced nail art and lash training by request"), "Mona Luxe training system is represented");
assert.ok(html.includes("delivery-ready social brand kit"), "Mona Luxe social brand system is represented");
assert.ok(html.includes('href="https://pdm-namibia.pages.dev/"'), "PDM Namibia live experience is linked");
assert.ok(html.includes('href="https://github.com/freeman-ipumbu/pdm-namibia-case-study"'), "PDM Namibia case study is linked");
assert.ok(html.includes("projects/pdm-namibia-hq.png"), "PDM Namibia uses the high-resolution identity banner");
assert.ok(html.includes('href="https://namair-command.pages.dev/"'), "NamAir uses its Git-connected Pages demo");
assert.ok(html.includes('href="https://nammar.pages.dev/"'), "NamMar uses its Git-connected Pages demo");
assert.ok(!html.includes("nammar-command-centre.freeman-ipumbu634390.chatgpt.site"), "Legacy NamMar host is removed");
assert.ok(html.includes('documents/Freeman-Paul-Ipumbu-Career-Dossier-2026.pdf'), "Approved career dossier is linked");
assert.ok(html.includes('download>Download career dossier</a>'), "Career dossier is prominent in the hero");
const dossier = fs.readFileSync(path.join(root, "documents/Freeman-Paul-Ipumbu-Career-Dossier-2026.pdf"));
assert.equal(dossier.subarray(0, 5).toString("ascii"), "%PDF-", "Career dossier must be a valid PDF");
assert.ok(dossier.length < 2 * 1024 * 1024, "Career dossier stays lightweight for public download");

const cards = [...html.matchAll(/<article class="build-card/g)].length;
assert.equal(cards, 23, "Selected build count changed; update the portfolio metric and test intentionally");
assert.ok(html.includes('<strong>23</strong><span>SELECTED BUILDS</span>'), "Hero build metric matches the cards");

for (const match of html.matchAll(/(?:src|href)="([^"#][^"]*)"/g)) {
  const value = match[1];
  if (/^(?:https?:|mailto:|tel:|\/)/.test(value)) continue;
  if (/[+'`]/.test(value)) continue; // Runtime-generated markup is verified by its source data.
  assert.ok(fs.existsSync(path.join(root, value)), `Missing local asset: ${value}`);
}

const image = fs.readFileSync(path.join(root, "social-preview-v3.jpg"));
assert.deepEqual([...image.subarray(0, 2)], [255,216], "Social preview must be JPEG");
assert.ok(image.length < 300 * 1024, "Social preview stays lightweight for messaging-app crawlers");

const runnerzProof = fs.readFileSync(path.join(root, "projects/runnerz-1.1.0.png"));
assert.deepEqual([...runnerzProof.subarray(0, 8)], [137,80,78,71,13,10,26,10], "Runnerz proof must be PNG");
assert.equal(runnerzProof.readUInt32BE(16), 1600, "Runnerz proof width");
assert.equal(runnerzProof.readUInt32BE(20), 900, "Runnerz proof height");

const unifiedProof = fs.readFileSync(path.join(root, "projects/unified-20-command-deck.png"));
assert.deepEqual([...unifiedProof.subarray(0, 8)], [137,80,78,71,13,10,26,10], "UNIFIED proof must be PNG");
assert.equal(unifiedProof.readUInt32BE(16), 1200, "UNIFIED proof width");
assert.equal(unifiedProof.readUInt32BE(20), 2664, "UNIFIED proof height");

console.log("PASS: portfolio metadata, accessibility landmarks, asset references, build count and social image.");
